<?php

declare(strict_types=1);

namespace RPWebDevelopment\WebviewDetect\Properties;

trait MiscBrowsers
{
    protected array $miscBrowsers = [
        [
            'name' => 'Yandex Browser',
            'match' => 'YaBrowser',
            'exclude' => 'YaApp_',
            'matches' => '/YaBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Edge',
            'match' => 'Edg',
            'exclude' => '',
            'matches' => '/Edg(|e|A|iOS)\/([0-9]+)\./',
            'num' => 2,
        ],
        [
            'name' => 'Opera',
            'match' => ' OPR/',
            'exclude' => 'Opera Mini|OPiOS|OPT/|OPRGX/|AlohaBrowser',
            'matches' => '/OPR\/(\d+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera',
            'match' => 'Opera',
            'exclude' => 'Opera Mini|OPiOS|OPT/|InettvBrowser/',
            'matches' => '/Opera.*Version\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera',
            'match' => 'Opera',
            'exclude' => 'Opera Mini|OPiOS|OPT/|InettvBrowser/',
            'matches' => '/Opera(\s|\/)([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'UC Browser',
            'match' => 'UBrowser|UCBrowser|UCMini',
            'exclude' => 'UCTurbo|AliApp',
            'matches' => '/(UBrowser|UCBrowser|UCMini)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'UC Browser Turbo',
            'match' => 'UCTurbo/',
            'exclude' => '',
            'matches' => '/UCTurbo\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Puffin',
            'match' => 'Puffin/',
            'exclude' => '',
            'matches' => '/Puffin\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Vivaldi',
            'match' => 'Vivaldi/',
            'exclude' => '',
            'matches' => '/Vivaldi\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'QQ Browser',
            'match' => 'QQBrowser/',
            'exclude' => '',
            'matches' => '/QQBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Coc Coc',
            'match' => 'coc_coc_browser',
            'exclude' => '',
            'matches' => '/coc_coc_browser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Whale',
            'match' => 'Whale/',
            'exclude' => 'NAVER(inapp;',
            'matches' => '/Whale\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Brave',
            'match' => 'Brave',
            'exclude' => '',
            'matches' => '/Brave(?: Chrome)?\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Maxthon',
            'match' => 'Maxthon/',
            'exclude' => '',
            'matches' => '/Maxthon\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Maxthon',
            'match' => 'MxBrowser/',
            'exclude' => '',
            'matches' => '/MxBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => '2345 Explorer',
            'match' => '2345Explorer|2345Browser',
            'exclude' => '',
            'matches' => '/(2345Explorer|2345Browser)(?: |\/)?([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'IceCat',
            'match' => 'IceCat/',
            'exclude' => '',
            'matches' => '/IceCat\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Lunascape',
            'match' => 'Lunascape',
            'exclude' => '',
            'matches' => '/Lunascape(?: |\/)?([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Seznam Browser',
            'match' => 'Seznam.cz/|SznProhlizec/',
            'exclude' => '',
            'matches' => '/(Seznam\.cz|SznProhlizec)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Sleipnir',
            'match' => 'Sleipnir/',
            'exclude' => '',
            'matches' => '/Sleipnir\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Sputnik',
            'match' => 'SputnikBrowser/',
            'exclude' => '',
            'matches' => '/SputnikBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Oculus Browser',
            'match' => 'OculusBrowser/',
            'exclude' => '',
            'matches' => '/OculusBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'PaleMoon',
            'match' => 'PaleMoon',
            'exclude' => '',
            'matches' => '/PaleMoon\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'SalamWeb',
            'match' => 'SalamWeb|Salam Browser',
            'exclude' => '',
            'matches' => '/SalamWeb\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Swing',
            'match' => 'Swing/|Swing(And)/',
            'exclude' => '',
            'matches' => '/Swing(?:\(And\))?\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Safe Exam Browser',
            'match' => 'SEB/',
            'exclude' => '',
            'matches' => '/SEB\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Colibri',
            'match' => 'Colibri/',
            'exclude' => '',
            'matches' => '/Colibri\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera GX',
            'match' => 'OPRGX',
            'exclude' => '',
            'matches' => '/OPRGX\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera GX',
            'match' => 'OPX/',
            'exclude' => '',
            'matches' => '/OPX\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Xvast',
            'match' => 'Xvast/',
            'exclude' => '',
            'matches' => '/Xvast\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Atom',
            'match' => 'Atom/',
            'exclude' => '',
            'matches' => '/Atom\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'NetCast',
            'match' => 'SmartTV/',
            'exclude' => '',
            'matches' => '/SmartTV\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'LG Browser',
            'match' => ' LG Browser/',
            'exclude' => '',
            'matches' => '/\sLG\sBrowser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Ghostery Browser',
            'match' => 'Ghostery:',
            'exclude' => '',
            'matches' => '/Ghostery\:([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Aloha Browser',
            'match' => 'AlohaBrowser/',
            'exclude' => '',
            'matches' => '/AlohaBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Lenovo Browser',
            'match' => 'SLBrowser/',
            'exclude' => '',
            'matches' => '/SLBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Samsung Browser TV',
            'match' => '/SamsungBrowser\/[.0-9]+\sTV\s/',
            'exclude' => '',
            'matches' => '/SamsungBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'WeChat App',
            'match' => 'MicroMessenger/',
            'exclude' => '',
            'matches' => '/MicroMessenger\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'WKWebView',
            'match' => '/Intel\sMac\sOS\sX\s\d+.*\)\sAppleWebKit\/[.0-9]+.*Gecko\)$/',
            'exclude' => '',
            'matches' => 'AppleWebKit',
            'num' => 1,
        ],
        [
            'name' => 'Sber Browser',
            'match' => 'SberBrowser/',
            'exclude' => '',
            'matches' => '/SberBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
    ];
}
