<?php

declare(strict_types=1);

namespace RPWebDevelopment\WebviewDetect\Properties;

trait MobileBrowsers
{
    protected array $mobileBrowsers = [
        [
            'name' => 'Safari Mobile',
            'match' => '/(iPhone|iphone|iPad;|iPod).*AppleWebKit\/[.0-9]+\s\(KHTML,\slike\sGecko\)\s.*Version\/[.,0-9]+\sMobile\//',
            'exclude' => 'RDDocuments|AlohaBrowser|DuckDuckGo|MiuiBrowser|Snapchat|NAVER(inapp;|1Password|OPT/|Ddg/',
            'matches' => '/Version\/([0-9]+\.[0-9]+)(|\.[0-9]+|\,[0-9]+)\sMobile\//',
            'num' => 1,
        ],
        [
            'name' => 'Safari Mobile',
            'match' => '/(Intel\sMac\sOS\sX).*AppleWebKit\/.*Version\/[.,0-9]+\s(?:|Mobile\/\w+\s)Safari\/[.0-9A-Za-z]+(|\/[0-9]+|\s\(.*\))+$/',
            'exclude' => 'CriOS|RDDocuments|AlohaBrowser|DuckDuckGo|MiuiBrowser|Snapchat|NAVER(inapp;|1Password|OPT/|Ddg/',
            'matches' => '/Version\/([0-9]+\.[0-9]+)(|\.[0-9]+|\,[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Android Browser',
            'match' => '/Android.*Version\/[.0-9]+\s(?:Mobile\s)?Safari\/[.0-9]+(|\-[0-9]+)$/',
            'exclude' => 'Chrome/',
            'matches' => '/Android.*Version\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Android Browser',
            'match' => 'Dalvik/',
            'exclude' => 'Chrome/',
            'matches' => '/Dalvik\/([.0-9]+)\s\(Linux;\sU;\sAndroid\s/',
            'num' => 2,
        ],
        [
            'name' => 'Samsung Browser',
            'match' => 'SamsungBrowser',
            'exclude' => 'CrossApp',
            'matches' => '/SamsungBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Firefox Focus',
            'match' => 'Focus/',
            'exclude' => '',
            'matches' => '/Focus\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Firefox iOS',
            'match' => 'FxiOS',
            'exclude' => '',
            'matches' => '/FxiOS\/([0-9]*[.]?[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera Mini',
            'match' => 'Opera Mini|OPiOS',
            'exclude' => '',
            'matches' => '/(Opera Mini|OPiOS)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Opera Touch',
            'match' => 'OPT/',
            'exclude' => '',
            'matches' => '/OPT\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Huawei Browser',
            'match' => 'HuaweiBrowser/',
            'exclude' => '',
            'matches' => '/HuaweiBrowser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'DuckDuckGo',
            'match' => 'DuckDuckGo/',
            'exclude' => '',
            'matches' => '/DuckDuckGo\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'DuckDuckGo',
            'match' => 'Ddg/',
            'exclude' => '',
            'matches' => '/Ddg\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Mi Browser',
            'match' => 'MiuiBrowser/',
            'exclude' => '',
            'matches' => '/MiuiBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Mint Browser',
            'match' => 'Mint Browser/',
            'exclude' => '',
            'matches' => '/Mint\sBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Avast Browser',
            'match' => 'AvastSecureBrowser/',
            'exclude' => '',
            'matches' => '/AvastSecureBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Google App',
            'match' => '/(iPhone|iphone|iPad;|iPod).*\)\sGSA\/([0-9]+)/',
            'exclude' => '',
            'matches' => '/(iPhone|iphone|iPad;|iPod).*\)\sGSA\/([0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Google App',
            'match' => '/\sGSA\//',
            'exclude' => '',
            'matches' => '/\sGSA\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Facebook App',
            'match' => 'FBAV/|FBSV/',
            'exclude' => 'FBAN/Messenger|FB_IAB/MESSENGER',
            'matches' => '/(FBAV|FBSV)\/([0-9]+)\./',
            'num' => 2,
        ],
        [
            'name' => 'Instagram App',
            'match' => 'Instagram',
            'exclude' => '',
            'matches' => '/Instagram\s([0-9]+)\./',
            'num' => 1,
        ],
        [
            'name' => 'Facebook Messenger',
            'match' => 'FBAN/Messenger|FB_IAB/MESSENGER',
            'exclude' => '',
            'matches' => '/(FBAV|FBSV)\/([0-9]+)\./',
            'num' => 2,
        ],
        [
            'name' => 'Snapchat',
            'match' => 'Snapchat',
            'exclude' => '',
            'matches' => '/\sSnapchat\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'WhatsApp',
            'match' => 'WhatsApp',
            'exclude' => '',
            'matches' => '/WhatsApp\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Viber',
            'match' => 'Viber/',
            'exclude' => '',
            'matches' => '/Viber\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Yandex App',
            'match' => 'YaApp_',
            'exclude' => '',
            'matches' => '/YaApp_(Android|iOS)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Yandex App',
            'match' => 'YandexSearch/',
            'exclude' => '',
            'matches' => '/YandexSearch\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Yandex App',
            'match' => 'YaSearchBrowser/',
            'exclude' => '',
            'matches' => '/YaSearchBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Dolfin',
            'match' => 'Dolfin/',
            'exclude' => '',
            'matches' => '/Dolfin\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Flipboard App',
            'match' => 'Flipboard/',
            'exclude' => '',
            'matches' => '/Flipboard\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'FreeU',
            'match' => 'FreeU|Freeu',
            'exclude' => '',
            'matches' => '/(FreeU|Freeu)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Iron',
            'match' => 'Iron Safari|MobileIron',
            'exclude' => '',
            'matches' => '/Chrome\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Sogou Mobile Browser',
            'match' => 'SogouMobileBrowser/',
            'exclude' => '',
            'matches' => '/SogouMobileBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Meizu Browser',
            'match' => 'MZBrowser/',
            'exclude' => '',
            'matches' => '/MZBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => '360 Mobile Browser',
            'match' => '360 Aphone',
            'exclude' => '',
            'matches' => '/360\sAphone\sBrowser\s\(([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Adblock Browser',
            'match' => 'ABB/',
            'exclude' => '',
            'matches' => '/ABB\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Ecosia Browser',
            'match' => 'Ecosia',
            'exclude' => '',
            'matches' => '/Chrome\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'HeyTap Browser',
            'match' => 'HeyTapBrowser/',
            'exclude' => '',
            'matches' => '/HeyTapBrowser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Oppo Browser',
            'match' => 'OppoBrowser/',
            'exclude' => '',
            'matches' => '/OppoBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Silk',
            'match' => 'Silk/',
            'exclude' => '',
            'matches' => '/Silk\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Surf Browser',
            'match' => 'SurfBrowser/',
            'exclude' => '',
            'matches' => '/SurfBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Phoenix Browser',
            'match' => 'PHX/',
            'exclude' => '',
            'matches' => '/PHX\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'CM Mobile',
            'match' => 'ACHEETAHI',
            'exclude' => '',
            'matches' => '/Chrome\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Bing App',
            'match' => ' BingWeb',
            'exclude' => '',
            'matches' => '/BingWeb\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Firefox Klar',
            'match' => 'Klar/',
            'exclude' => '',
            'matches' => '/Klar\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Super Fast Browser',
            'match' => 'SFBrowser|tssomas',
            'exclude' => '',
            'matches' => '/(SFBrowser|tssomas)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Tenta Browser',
            'match' => 'Tenta/',
            'exclude' => '',
            'matches' => '/Tenta\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Kiwi Browser',
            'match' => 'Kiwi Chrome/',
            'exclude' => '',
            'matches' => '/Kiwi\sChrome\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'JioPages',
            'match' => 'JioBrowser/',
            'exclude' => '',
            'matches' => '/JioBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'JioPages',
            'match' => 'JioPages/',
            'exclude' => '',
            'matches' => '/JioPages\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Qwant Mobile',
            'match' => 'QwantBrowser',
            'exclude' => '',
            'matches' => '/QwantBrowser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Qwant Mobile',
            'match' => 'QwantMobile',
            'exclude' => '',
            'matches' => '/QwantMobile\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Cake Browser',
            'match' => '; Cake) ',
            'exclude' => '',
            'matches' => '/\;\sCake\).*AppleWebKit.*Version\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'DU Browser',
            'match' => 'bdbrowser',
            'exclude' => '',
            'matches' => '/bdbrowser(|_i18n)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'DU Browser',
            'match' => 'baidubrowser',
            'exclude' => '',
            'matches' => '/baidubrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Baidu Search App',
            'match' => 'baiduboxapp/',
            'exclude' => '',
            'matches' => '/baiduboxapp\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'DU Browser HD',
            'match' => 'BaiduHD/',
            'exclude' => '',
            'matches' => '/BaiduHD\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Hi Browser',
            'match' => 'HiBrowser/',
            'exclude' => '',
            'matches' => '/HiBrowser\/?(?:v)?([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'VmWare Browser',
            'match' => 'AirWatch Browser',
            'exclude' => '',
            'matches' => '/AirWatch\sBrowser\sv([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Iron Mobile',
            'match' => 'MobileIron/',
            'exclude' => '',
            'matches' => '/MobileIron\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'NineSky',
            'match' => 'Ninesky-android-mobile/',
            'exclude' => '',
            'matches' => '/Ninesky\-android\-mobile\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Realme Browser',
            'match' => 'RealmeBrowser/',
            'exclude' => '',
            'matches' => '/RealmeBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Vivo Browser',
            'match' => 'VivoBrowser/',
            'exclude' => '',
            'matches' => '/VivoBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Web Explorer',
            'match' => 'Web Explorer/',
            'exclude' => '',
            'matches' => '/Web\sExplorer\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'NTENT Browser',
            'match' => 'NTENTBrowser/',
            'exclude' => '',
            'matches' => '/NTENTBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Nox Browser',
            'match' => 'NoxBrowser/',
            'exclude' => '',
            'matches' => '/NoxBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Quark Browser',
            'match' => 'Quark/',
            'exclude' => '',
            'matches' => '/Quark\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Yaani Browser',
            'match' => 'YaaniBrowser',
            'exclude' => '',
            'matches' => '/YaaniBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Tizen Browser',
            'match' => '/Tizen(?: )?(?:\/)?[.0-9]+.*AppleWebKit\/.*(Version|SLP Browser|Tizen Browser|TizenBrowser)\/([0-9]+\.[0-9]+)/',
            'exclude' => '',
            'matches' => '/Tizen(?: )?(?:\/)?[.0-9]+.*AppleWebKit\/.*(Version|SLP Browser|Tizen Browser|TizenBrowser)\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Internet Explorer Mobile',
            'match' => 'IEMobile',
            'exclude' => '',
            'matches' => '/IEMobile(?: )?(?:\/)?([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Internet Explorer Mobile',
            'match' => 'Trident/',
            'exclude' => '',
            'matches' => '/Trident\/[.0-9].*Touch;*.rv\:([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'ZetaKey',
            'match' => 'Zetakey/',
            'exclude' => '',
            'matches' => '/Zetakey\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Nokia Browser',
            'match' => 'NokiaBrowser/',
            'exclude' => '',
            'matches' => '/NokiaBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'NetFront',
            'match' => 'NetFront/',
            'exclude' => '',
            'matches' => '/NetFront\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'BlackBerry Browser',
            'match' => '/(BB10;|BlackBerry|PlayBook).*AppleWebKit.*Version\/([0-9]+\.[0-9]+)/',
            'exclude' => '',
            'matches' => '/(BB10;|BlackBerry|PlayBook).*AppleWebKit.*Version\/([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'ONE Browser',
            'match' => 'OneBrowser/',
            'exclude' => '',
            'matches' => '/OneBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Web Explorer',
            'match' => 'webexplorer/',
            'exclude' => '',
            'matches' => '/webexplorer\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Start Internet Browser',
            'match' => 'Start/',
            'exclude' => '',
            'matches' => '/Start\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'EUI Browser',
            'match' => 'EUI Browser',
            'exclude' => '',
            'matches' => '/EUI\sBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'iCab Mobile',
            'match' => 'iCabMobile',
            'exclude' => '',
            'matches' => '/iCabMobile(\s|\/)([0-9]+\.[0-9]+)/',
            'num' => 2,
        ],
        [
            'name' => 'Mercury',
            'match' => 'Mercury/',
            'exclude' => '',
            'matches' => '/Mercury\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Samsung Browser',
            'match' => '; SAMSUNG S|; SAMSUNG G',
            'exclude' => 'SamsungBrowser',
            'matches' => '/\;\sSAMSUNG\s(S|G)+.*\sBuild\/.*\)\sAppleWebKit\/.*Version\/([0-9]+\.[0-9]+)\sChrome\/[.0-9]+.*\sSafari\/[.0-9]+$/',
            'num' => 2,
        ],
        [
            'name' => 'Documents App',
            'match' => 'RDDocuments/',
            'exclude' => '',
            'matches' => '/RDDocuments\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Opera Coast',
            'match' => 'Coast/',
            'exclude' => '',
            'matches' => '/Coast\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Android Browser',
            'match' => '/Android.*Version\/[.0-9]+\s(?:Mobile\s)?Safari(|\/[.0-9]+\sCyanogenMod.*)+$/',
            'exclude' => 'Chrome/',
            'matches' => '/Android.*Version\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Playstation Browser',
            'match' => '/(PlayStation\s|PLAYSTATION\s)/',
            'exclude' => '',
            'matches' => '/(PlayStation\s|PLAYSTATION\s)/',
            'num' => 1,
        ],
        [
            'name' => 'Naver App',
            'match' => 'NAVER(inapp;',
            'exclude' => '',
            'matches' => '/NAVER\(inapp;\ssearch;\s\d+;\s([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Line App',
            'match' => ' Line/',
            'exclude' => '',
            'matches' => '/\sLine\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'QQ App',
            'match' => ' QQ/',
            'exclude' => '',
            'matches' => '/\sQQ\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'GNews App',
            'match' => ' GNews ',
            'exclude' => '',
            'matches' => '/\sGNews\s.*\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => '1Password App',
            'match' => '1Password',
            'exclude' => '',
            'matches' => '/\s1Password\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Pinterest App',
            'match' => 'Pinterest',
            'exclude' => '',
            'matches' => '/Pinterest/',
            'num' => 1,
        ],
        [
            'name' => 'Twitter App',
            'match' => ' Twitter',
            'exclude' => '',
            'matches' => '/Twitter/',
            'num' => 1,
        ],
        [
            'name' => 'Ali App',
            'match' => ' AliApp',
            'exclude' => '',
            'matches' => '/\sAliApp/',
            'num' => 1,
        ],
        [
            'name' => 'Alipay',
            'match' => 'AlipayClient',
            'exclude' => '',
            'matches' => '/AlipayClient\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Samsung CrossApp',
            'match' => 'CrossApp/',
            'exclude' => '',
            'matches' => '/CrossApp\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Diigo',
            'match' => 'DiigoBrowser',
            'exclude' => '',
            'matches' => '/DiigoBrowser/',
            'num' => 1,
        ],
        [
            'name' => 'Stargon',
            'match' => 'Stargon/',
            'exclude' => '',
            'matches' => '/Stargon\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'You Browser',
            'match' => 'YouBrowser/',
            'exclude' => '',
            'matches' => '/YouBrowser\/([0-9]+\.[0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Max Browser',
            'match' => 'MaxBrowser/',
            'exclude' => '',
            'matches' => '/MaxBrowser\/([0-9]+)/',
            'num' => 1,
        ],
        [
            'name' => 'Soul Browser',
            'match' => 'Soul/',
            'exclude' => '',
            'matches' => '/Soul\/([0-9]+)/',
            'num' => 1,
        ],
    ];
}
